-- Store-admin permissions become one catalogue: area.view / .create / .edit / .delete
-- (PERMISSION_AREAS in @ecom/shared-types). Built-in roles get the lists from store-roles.ts;
-- roles a store made itself have their old codes translated.

CREATE TEMP TABLE _new_role_perms ("slug" TEXT, "permission" TEXT);
INSERT INTO _new_role_perms VALUES
  ('owner', '*'),
  ('product_manager', 'dashboard.view'),
  ('product_manager', 'products.view'),
  ('product_manager', 'products.create'),
  ('product_manager', 'products.edit'),
  ('product_manager', 'products.delete'),
  ('product_manager', 'categories.view'),
  ('product_manager', 'categories.create'),
  ('product_manager', 'categories.edit'),
  ('product_manager', 'categories.delete'),
  ('product_manager', 'attributes.view'),
  ('product_manager', 'attributes.create'),
  ('product_manager', 'attributes.edit'),
  ('product_manager', 'attributes.delete'),
  ('product_manager', 'media.view'),
  ('product_manager', 'media.create'),
  ('product_manager', 'media.edit'),
  ('product_manager', 'media.delete'),
  ('product_manager', 'inventory.view'),
  ('product_manager', 'inventory.edit'),
  ('product_manager', 'reviews.view'),
  ('order_manager', 'dashboard.view'),
  ('order_manager', 'orders.view'),
  ('order_manager', 'orders.create'),
  ('order_manager', 'orders.edit'),
  ('order_manager', 'customers.view'),
  ('order_manager', 'customers.create'),
  ('order_manager', 'customers.edit'),
  ('order_manager', 'products.view'),
  ('order_manager', 'inventory.view'),
  ('order_manager', 'shipping.view'),
  ('customer_support', 'orders.view'),
  ('customer_support', 'orders.create'),
  ('customer_support', 'customers.view'),
  ('customer_support', 'customers.create'),
  ('customer_support', 'customers.edit'),
  ('customer_support', 'reviews.view'),
  ('customer_support', 'reviews.edit'),
  ('customer_support', 'products.view'),
  ('marketing', 'dashboard.view'),
  ('marketing', 'coupons.view'),
  ('marketing', 'coupons.create'),
  ('marketing', 'coupons.edit'),
  ('marketing', 'coupons.delete'),
  ('marketing', 'flash_sales.view'),
  ('marketing', 'flash_sales.create'),
  ('marketing', 'flash_sales.edit'),
  ('marketing', 'flash_sales.delete'),
  ('marketing', 'reviews.view'),
  ('marketing', 'reviews.edit'),
  ('marketing', 'reviews.delete'),
  ('marketing', 'products.view'),
  ('marketing', 'categories.view'),
  ('marketing', 'customers.view'),
  ('marketing', 'emails.view'),
  ('marketing', 'emails.edit'),
  ('content', 'pages.view'),
  ('content', 'pages.create'),
  ('content', 'pages.edit'),
  ('content', 'pages.delete'),
  ('content', 'blog.view'),
  ('content', 'blog.create'),
  ('content', 'blog.edit'),
  ('content', 'blog.delete'),
  ('content', 'faqs.view'),
  ('content', 'faqs.create'),
  ('content', 'faqs.edit'),
  ('content', 'faqs.delete'),
  ('content', 'menus.view'),
  ('content', 'menus.create'),
  ('content', 'menus.edit'),
  ('content', 'menus.delete'),
  ('content', 'online_store.view'),
  ('content', 'online_store.edit'),
  ('content', 'media.view'),
  ('content', 'media.create'),
  ('content', 'products.view'),
  ('content', 'categories.view'),
  ('finance', 'dashboard.view'),
  ('finance', 'orders.view'),
  ('finance', 'orders.edit'),
  ('finance', 'customers.view'),
  ('finance', 'taxes.view'),
  ('finance', 'taxes.create'),
  ('finance', 'taxes.edit'),
  ('finance', 'taxes.delete'),
  ('finance', 'settings.view'),
  ('finance', 'audit_logs.view'),
  ('shipper', 'orders.view'),
  ('shipper', 'orders.edit'),
  ('shipper', 'shipping.view'),
  ('shipper', 'inventory.view'),
  ('reports', 'dashboard.view'),
  ('reports', 'orders.view'),
  ('reports', 'customers.view'),
  ('reports', 'products.view'),
  ('reports', 'inventory.view'),
  ('viewer', 'dashboard.view'),
  ('viewer', 'orders.view'),
  ('viewer', 'products.view'),
  ('viewer', 'categories.view'),
  ('viewer', 'attributes.view'),
  ('viewer', 'media.view'),
  ('viewer', 'inventory.view'),
  ('viewer', 'customers.view'),
  ('viewer', 'reviews.view'),
  ('viewer', 'coupons.view'),
  ('viewer', 'flash_sales.view'),
  ('viewer', 'pages.view'),
  ('viewer', 'blog.view'),
  ('viewer', 'faqs.view'),
  ('viewer', 'menus.view'),
  ('viewer', 'online_store.view'),
  ('viewer', 'shipping.view'),
  ('viewer', 'taxes.view'),
  ('viewer', 'settings.view'),
  ('viewer', 'emails.view');

CREATE TEMP TABLE _valid_perms ("permission" TEXT);
INSERT INTO _valid_perms VALUES
  ('dashboard.view'),
  ('orders.view'),
  ('orders.create'),
  ('orders.edit'),
  ('products.view'),
  ('products.create'),
  ('products.edit'),
  ('products.delete'),
  ('categories.view'),
  ('categories.create'),
  ('categories.edit'),
  ('categories.delete'),
  ('attributes.view'),
  ('attributes.create'),
  ('attributes.edit'),
  ('attributes.delete'),
  ('media.view'),
  ('media.create'),
  ('media.edit'),
  ('media.delete'),
  ('inventory.view'),
  ('inventory.edit'),
  ('customers.view'),
  ('customers.create'),
  ('customers.edit'),
  ('customers.delete'),
  ('reviews.view'),
  ('reviews.edit'),
  ('reviews.delete'),
  ('coupons.view'),
  ('coupons.create'),
  ('coupons.edit'),
  ('coupons.delete'),
  ('flash_sales.view'),
  ('flash_sales.create'),
  ('flash_sales.edit'),
  ('flash_sales.delete'),
  ('pages.view'),
  ('pages.create'),
  ('pages.edit'),
  ('pages.delete'),
  ('blog.view'),
  ('blog.create'),
  ('blog.edit'),
  ('blog.delete'),
  ('faqs.view'),
  ('faqs.create'),
  ('faqs.edit'),
  ('faqs.delete'),
  ('menus.view'),
  ('menus.create'),
  ('menus.edit'),
  ('menus.delete'),
  ('online_store.view'),
  ('online_store.edit'),
  ('shipping.view'),
  ('shipping.create'),
  ('shipping.edit'),
  ('shipping.delete'),
  ('taxes.view'),
  ('taxes.create'),
  ('taxes.edit'),
  ('taxes.delete'),
  ('settings.view'),
  ('settings.edit'),
  ('emails.view'),
  ('emails.edit'),
  ('staff.view'),
  ('staff.create'),
  ('staff.edit'),
  ('staff.delete'),
  ('roles.view'),
  ('roles.create'),
  ('roles.edit'),
  ('roles.delete'),
  ('audit_logs.view');

CREATE TEMP TABLE _legacy_area ("prefix" TEXT, "area" TEXT);
INSERT INTO _legacy_area VALUES
  ('products', 'products'),
  ('collections', 'products'),
  ('categories', 'categories'),
  ('brands', 'categories'),
  ('attributes', 'attributes'),
  ('media', 'media'),
  ('inventory', 'inventory'),
  ('orders', 'orders'),
  ('shipments', 'orders'),
  ('invoices', 'orders'),
  ('refunds', 'orders'),
  ('returns', 'orders'),
  ('payments', 'orders'),
  ('customers', 'customers'),
  ('reviews', 'reviews'),
  ('coupons', 'coupons'),
  ('flash_sales', 'flash_sales'),
  ('pages', 'pages'),
  ('blog', 'blog'),
  ('faqs', 'faqs'),
  ('menus', 'menus'),
  ('themes', 'online_store'),
  ('homepage_sections', 'online_store'),
  ('page_builder', 'online_store'),
  ('shipping', 'shipping'),
  ('reports', 'dashboard'),
  ('dashboard', 'dashboard'),
  ('email_templates', 'emails'),
  ('settings', 'settings'),
  ('admin.users', 'staff'),
  ('rbac.roles', 'roles');

CREATE TEMP TABLE _legacy_action ("action" TEXT, "new_action" TEXT);
INSERT INTO _legacy_action VALUES
  ('read', 'view'),
  ('view', 'view'),
  ('export', 'view'),
  ('print', 'view'),
  ('create', 'create'),
  ('update', 'edit'),
  ('edit', 'edit'),
  ('statusChange', 'edit'),
  ('manage', 'edit'),
  ('notes', 'edit'),
  ('assignRole', 'edit'),
  ('resetPassword', 'edit'),
  ('delete', 'delete');

-- 1. Custom roles: translate "prefix.action" (and "prefix.*" = every action of the area).
CREATE TEMP TABLE _custom AS
SELECT DISTINCT p."roleId", la."area" || '.' || COALESCE(lx."new_action", '*') AS "permission"
FROM "PermissionAssignment" p
JOIN "Role" r ON r."id" = p."roleId" AND NOT r."isSystem"
JOIN _legacy_area la ON p."permission" LIKE la."prefix" || '.%'
LEFT JOIN _legacy_action lx ON lx."action" = substring(p."permission" FROM length(la."prefix") + 2)
WHERE p."permission" <> '*'
  AND (lx."new_action" IS NOT NULL OR substring(p."permission" FROM length(la."prefix") + 2) = '*');

CREATE TEMP TABLE _custom_expanded AS
SELECT DISTINCT c."roleId", v."permission"
FROM _custom c
JOIN _valid_perms v ON v."permission" = c."permission"
   OR (c."permission" LIKE '%.*' AND v."permission" LIKE replace(c."permission", '*', '') || '%');

DELETE FROM "PermissionAssignment" p
USING "Role" r
WHERE r."id" = p."roleId" AND NOT r."isSystem" AND p."permission" <> '*';

INSERT INTO "PermissionAssignment" ("roleId", "permission")
SELECT "roleId", "permission" FROM _custom_expanded;

-- 2. Built-in roles: replace with the new defaults.
DELETE FROM "PermissionAssignment" p USING "Role" r WHERE r."id" = p."roleId" AND r."isSystem";

INSERT INTO "PermissionAssignment" ("roleId", "permission")
SELECT r."id", n."permission"
FROM "Role" r
JOIN _new_role_perms n ON n."slug" = r."slug"
WHERE r."isSystem";

DROP TABLE _new_role_perms, _valid_perms, _legacy_area, _legacy_action, _custom, _custom_expanded;
